# Generated by Django 4.2 on 2025-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50, unique=True, verbose_name='Código de barras del proveedor')),
                ('codigo_interno', models.CharField(max_length=12, unique=True)),
                ('desc_producto', models.CharField(max_length=100)),
                ('clasificacion', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=12)),
                ('marca', models.CharField(max_length=50)),
                ('p_costo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('p_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
